version: '3'

services:
  bqp-auth-profile-service:
    image: bqp-auth-profile-service
    container_name: bqp-auth-profile-service
    build:
      context: ./
      dockerfile: ./compose/local/Dockerfile
    command: /start
    env_file:
      - src/config/.env
    expose:
      - 6001
    volumes:
      - .:/app:z
    ports:
      - 6001:6001


networks:
  default:
    external:
      name: bqp_network